django/0302/00_django_intro/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('dtl-practice/', views.dtl_practice, name='dtl-practice'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('hello/<str:name>/', views.hello, name='hello'),
]

django/0302/00_django_intro/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

django/0302/00_django_intro/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

django/0302/00_django_intro/articles/views.py
from django.shortcuts import render
import random

def index(request):
    return render(request, 'articles/index.html')


def greeting(request):
    foods = ['apple', 'banana', 'coconut']
    info = {
        'name': 'Alice'
    }
    context = {
        'foods' : foods,
        'info' : info,
    }
    return render(request, 'articles/greeting.html', context)


def dinner(request):
    foods = ['카레', '삼겹살', '떡볶이', '김밥', '치킨']
    pick = random.choice(foods)
    context = {
        'pick': pick,
        'foods': foods,
    }
    return render(request, 'articles/dinner.html', context)


def dtl_practice(request):
    foods = ['짜장면', '탕수육', '짬뽕', '양장피']
    fruits = ['apple', 'banana', 'cucumber', 'mango']
    user_list = []
    context = {
        'foods': foods,
        'fruits': fruits,
        'user_list': user_list,
    }
    return render(request, 'articles/dtl_practice.html', context)


def throw(request):
    return render(request, 'articles/throw.html')


def catch(request):
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)


def hello(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/hello.html', context)

django/0302/00_django_intro/pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

django/0302/00_django_intro/articles/templates/articles/catch.html
{% extends 'base.html' %}
{% block content %}
  <h1>Catch</h1>
  <h2>여기서 {{ message }}를 받았어!!!</h2>
  <a href="{% url 'articles:throw' %}">다시 던지기</a>

{% endblock content %}

django/0302/00_django_intro/articles/templates/articles/dinner.html
{% extends 'base.html' %}
{% block content %}
  <h1>오늘 저녁은 {{ pick }}</h1>
  <p>{{ pick }}은 {{ pick | length}} 글자</p>
  <p>{{ foods | join:", "}} </p>
  {# 주석 #}
  {% comment %} 장고 주석 {% endcomment %}
  <!-- HTML 주석-->
  
  <p>메뉴판</p>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}

django/0302/00_django_intro/articles/templates/articles/dtl_practice.html
{% extends 'base.html' %}
{% block content %}
  <h3>1. for</h3>
{% for food in foods %}
  <p>{{ food }}</p>
{% endfor %}
<hr>

{% for food in foods %}
  <p>{{ forloop.counter }} {{ food }}</p>
{% endfor %}
<hr>

{% for user in empty_list %}
  <p>{{ user }}</p>
{% empty %}
  <p>지금 가입한 유저가 없습니다.</p>
{% endfor %}
<hr>


<h3>2. if</h3>
{% if '짜장면' in foods %}
  <p>짜장면엔 고추가루지 !</p>
{% endif %}
<hr>

{% for food in foods %}
  {% if forloop.first %}
    <p>짜장면+고추가루</p>
  {% else %}
    <p>{{ food }}</p>
  {% endif %}
{% endfor %}
<hr>

<p>3. length filter 활용</p>
{% for fruit in fruits %}
  {% if fruit|length > 5 %}
    <p>이름이 너무 길어요.</p>
  {% else %}
    <p>{{ fruit }}, {{ fruit|length }}</p>
  {% endif %}
{% endfor %}
<hr>

<h3>4. lorem ipsum</h3>
{% lorem %}
<hr>
{% lorem 3 w %}
<hr>
{% lorem 4 w random %}
<hr>
{% lorem 2 p %}
<hr>

<h3>5. 글자 관련 필터</h3>
<p>{{ 'ABC'|lower }}</p>
<p>{{ 'i love you'|title }}</p>
<p>{{ foods|random }}</p>
<hr>

<h3>6. 연산</h3>
<p>{{ 4|add:6 }}</p>
<hr>

<h3>7. 다양한 날짜 표현</h3>
{% now "DATETIME_FORMAT" %}<br>
{% now "SHORT_DATETIME_FORMAT" %}<br>
{% now "DATE_FORMAT" %}<br>
{% now "SHORT_DATE_FORMAT" %}
<hr>
{% now "Y년 m월 d일 (D) h:i" %}
<hr>
{% now "Y" as current_year %}
Copyright {{ current_year }}
<hr>

<a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}

django/0302/00_django_intro/articles/templates/articles/greeting.html
{% extends 'base.html' %}
{% block content %}
  <p>안녕하세요. {{ info.name }}입니다.</p>
  <p>제가 좋아하는 음식은 {{ foods }}</p>
  <p>제일 좋아하는 음식은  {{ foods.0 }}</p>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}

django/0302/00_django_intro/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
  <h1>만나서 반가워요 {{ name }} 님!</h1>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}

django/0302/00_django_intro/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>안녕하세요</h1>
  <a href="{% url 'articles:greeting' %}">greeting</a>
  <a href="{% url 'articles:dinner' %}">dinner</a>
  <a href="{% url 'articles:dtl-practice' %}">dtl-practice</a>

  <a href="{% url 'pages:index' %}">page의 index</a>
{% endblock content %}

django/0302/00_django_intro/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>Throw</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw</label>
    <input type="text" id="message" name="message">
    <input type="submit" value="전송">
  </form>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}