django/0310/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('new/', views.new, name = 'new'),
    path('create/', views.create, name = 'create'),
    path('<int:pk>/', views.detail, name = 'detail'),
    path('<int:pk>/delete/', views.delete, name = 'delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update')
    
]

django/0310/articles/models.py
from django.db import models

class Article(models.Model): #테이블
    title = models.CharField(max_length=10) 
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/0310/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

def index(request):

    articles = Article.objects.order_by('-pk')
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    article = Article(title=title, content=content)
    article.save()

    return redirect('articles:detail', article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk): #HTTP method가 POST일 경우에만 삭제될 수 있도록 조건 작성
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)    

django/0310/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<h2>{{article.title}}</h2>
<br>
<h3>{{article.content}}</h3>
<p>작성일: {{article.created_at}}</p>
<p>수정일: {{article.updated_at}}</p>
<a href="{%url 'articles:edit' article.pk%}" class = 'btn btn-primary'>EDIT</a>
<form action="{%url 'articles:delete' article.pk%}">
    {%csrf_token%}
    <button class = 'btn btn-danger'>DELETE</button>
</form>
<a href="{%url 'articles:index'%}">BACK</a>

{% endblock %}

django/0310/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block content %}

<h1>EDIT</h1>
<form action="{%url 'articles:update' article.pk%}" method = 'POST'>
    {% csrf_token %}
    <label for "title">TITLE: </label>
    <input type="text" name = 'title' value={{article.title}}>
    <br>
    <label for="content">CONTENT: </label>
    <textarea name="content" id="content" cols="30" rows="10">{{article.content}}</textarea>
    <br>
    <input type="submit" value="수정">
</form>
<a href="{% url 'articles:index' %}">BACK</a>

</form>

{% endblock content %}

django/0310/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content%}

<h1 class>INDEX</h1>
<a href="{% url 'articles:new' %}">NEW</a>
{%for article in articles%}
<h2>제목: {{article.title}} </h2>
<p>내용: {{article.content}} </p>
<a href="{%url 'articles:detail' article.pk%}">DETAIL</a>
{% endfor %}
{% endblock content%}

django/0310/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block content %}
<h1>NEW</h1>
<form action="{%url 'articles:create'%}" method = 'POST'>
    {% csrf_token %}
    <label for "title">TITLE: </label>
    <input type="text" name = 'title'>
    <br>
    <label for="content">CONTENT: </label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea>
    <br>
    <input type="submit" value="작성">
</form>
<a href="{% url 'articles:index' %}">BACK</a>
{% endblock content %}